name: project
channels:
  - conda-forge
dependencies:
  # Core runtime
  - python=3.10
  - pip

  # Core numerical & data handling
  - numpy>=1.21.0
  - scipy>=1.7.0
  - pandas>=1.3.0

  # Biology utilities
  - biopython>=1.79

  # Machine-learning / neighbour search
  - scikit-learn>=0.24.0
  - faiss-cpu>=1.7.0          # conda-forge provides CPU FAISS
  - python-annoy>=1.17.0      # package name on conda-forge for annoy
  - pymetis>=2023.1

  # High-performance helpers
  - numba>=0.53.0
  - joblib>=1.0.0

  # Visualisation (used in docs/examples)
  - matplotlib>=3.4.0

  # Optional: install your repo in editable mode if it has setup.py
  # or if you later add pyproject.toml. Leave commented if not needed.
  # - pip:
  #     - -e .
